name: flutter_bloc_base_template
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #svg
  flutter_svg: any

  #loading indicator
  loading_indicator: ^3.1.1

  #route
  auto_route: ^9.2.2

  #bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #log
  logger: ^2.5.0

  #dil
  easy_localization: any

  #network
  dio: ^5.7.0
  dartz: ^0.10.1

  #secure storage
  flutter_secure_storage: ^8.0.0

  #dependency injection
  get_it: ^7.6.7

  #utility
  kartal: any
  shared_preferences: ^2.3.3
  device_preview: ^1.2.0

  #firebase ve notification
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  pretty_dio_logger: ^1.3.1

  #device info
  device_info_plus: ^10.1.2
  uuid: ^4.5.1

  #toast message
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/splash/
    - assets/lang/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/font/Satoshi-Regular.ttf
        - asset: assets/font/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/font/Satoshi-Bold.ttf
          weight: 700
